services:
  steamapi:
    image: mcr.microsoft.com/dotnet/sdk:10.0
    volumes:
      - ./:/src:cached
    working_dir: /src
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
    command: ["dotnet", "run", "--project", "SteamAPI.csproj", "--urls", "http://+:8080"]
    ports:
      - "80:8080"
    restart: "always"